- name: Отключаем Cloud-Init для сетевой конфигурации
  copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      network: {config: disabled}

- name: Разворачиваем конфигурацию Netplan
  template:
    src: netplan_config.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
  notify: Apply Netplan

