- name: Отключаем Cloud-Init для сетевой конфигурации
  copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      network: {config: disabled}

- name: Настроить Netplan
  copy:
    dest: /etc/netplan/01-netcfg.yaml
    content: |
      network:
        version: 2
        ethernets:
          {{ public_iface }}:
            dhcp4: true
            dhcp6: false
          {{ private_iface }}:
            dhcp4: false
            dhcp6: false
            addresses:
              - {{ ansible_host }}/24
            routes:
              - to: default
                via: {{ gateway_ip }}
            nameservers:
              addresses:
                {% for dns in dns_servers %}
                - {{ dns }}
                {% endfor %}
  notify: Apply Netplan

