all:
  children:
    router:
      hosts:
        vm1:
          ansible_host: "{{ lookup('env', 'ANSIBLE_JUMP_HOST') }}"
          ansible_user: root
    workers:
      hosts:
        vm2:
          ansible_host: 192.168.0.6
          ansible_user: root
        vm3:
          ansible_host: 192.168.0.7
          ansible_user: root
