- name: Включаем IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
    state: present
  notify: Apply sysctl

- name: Добавляем NAT для внутренней сети
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: "{{ public_iface }}"
    state: present

- name: Сохраняем iptables
  shell: iptables-save > /etc/iptables.rules

- name: Применяем iptables при загрузке
  copy:
    dest: /etc/network/if-pre-up.d/iptables
    content: |
      #!/bin/sh
      iptables-restore < /etc/iptables.rules
    mode: '0755'