- name: Устанавливаем базовые пакеты
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ base_packages }}"

- name: Устанавливаем правильный timezone
  timezone:
    name: "Etc/UTC"
