- name: Устанавливаем базовые пакеты
  apt:
    name:
      - vim
      - curl
      - git
      - htop
      - net-tools
      - docker.io
    state: present
    update_cache: yes

- name: Устанавливаем правильный timezone
  timezone:
    name: "Etc/UTC"
